schema_version: 1

context:
  name: legend-pydataobj
  version: "1.17.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/legend_pydataobj-${{ version }}.tar.gz
  sha256: cb95c9535fdee8fa40ca5f51e8fb534126d3a5d99c4136fbadf4f9c476f71b37

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77
    - setuptools-scm >=7
  run:
    - python >=${{ python_min }}
    - awkward >=2
    - awkward-pandas
    - colorlog
    - h5py >=3.10
    - hdf5plugin
    - hist
    - numba !=0.53,!=0.54.*
    - numexpr
    - numpy >=1.21
    - pandas >=1.4.4
    - parse
    - pint >0.24
    - pint-pandas
tests:
  - python:
      imports:
        - lgdo
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip list
      - lh5ls --help
      - lh5concat --help

about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: LEGEND Python Data Objects
  description: |
    This package provides a Python implementation of the LEGEND Data Objects
    (LGDO) and I/O to HDF5, including Numba-accelerated custom compression
    algorithms for particle detector signals.
    More documentation is available in the
    [LEGEND data format specification](https://legend-exp.github.io/legend-data-format-specs).
  homepage: https://github.com/legend-exp/legend-pydataobj
  repository: https://github.com/legend-exp/legend-pydataobj
  documentation: https://legend-pydataobj.readthedocs.io/

extra:
  recipe-maintainers:
    - gipert
    - matthewfeickert
